package com.kiri.hackjak.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kiri.hackjak.db.Trayek;
import com.kiri.hackjak.db.TrayekRoute;
import com.kiri.hackjak.db.TrayekWaypoint;
import com.kiri.hackjak.db.TrayekRouteDetail;
import com.kiri.hackjak.db.Taxi;
import com.kiri.hackjak.db.TaxiPhone;

import com.kiri.hackjak.db.TrayekDao;
import com.kiri.hackjak.db.TrayekRouteDao;
import com.kiri.hackjak.db.TrayekWaypointDao;
import com.kiri.hackjak.db.TrayekRouteDetailDao;
import com.kiri.hackjak.db.TaxiDao;
import com.kiri.hackjak.db.TaxiPhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trayekDaoConfig;
    private final DaoConfig trayekRouteDaoConfig;
    private final DaoConfig trayekWaypointDaoConfig;
    private final DaoConfig trayekRouteDetailDaoConfig;
    private final DaoConfig taxiDaoConfig;
    private final DaoConfig taxiPhoneDaoConfig;

    private final TrayekDao trayekDao;
    private final TrayekRouteDao trayekRouteDao;
    private final TrayekWaypointDao trayekWaypointDao;
    private final TrayekRouteDetailDao trayekRouteDetailDao;
    private final TaxiDao taxiDao;
    private final TaxiPhoneDao taxiPhoneDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trayekDaoConfig = daoConfigMap.get(TrayekDao.class).clone();
        trayekDaoConfig.initIdentityScope(type);

        trayekRouteDaoConfig = daoConfigMap.get(TrayekRouteDao.class).clone();
        trayekRouteDaoConfig.initIdentityScope(type);

        trayekWaypointDaoConfig = daoConfigMap.get(TrayekWaypointDao.class).clone();
        trayekWaypointDaoConfig.initIdentityScope(type);

        trayekRouteDetailDaoConfig = daoConfigMap.get(TrayekRouteDetailDao.class).clone();
        trayekRouteDetailDaoConfig.initIdentityScope(type);

        taxiDaoConfig = daoConfigMap.get(TaxiDao.class).clone();
        taxiDaoConfig.initIdentityScope(type);

        taxiPhoneDaoConfig = daoConfigMap.get(TaxiPhoneDao.class).clone();
        taxiPhoneDaoConfig.initIdentityScope(type);

        trayekDao = new TrayekDao(trayekDaoConfig, this);
        trayekRouteDao = new TrayekRouteDao(trayekRouteDaoConfig, this);
        trayekWaypointDao = new TrayekWaypointDao(trayekWaypointDaoConfig, this);
        trayekRouteDetailDao = new TrayekRouteDetailDao(trayekRouteDetailDaoConfig, this);
        taxiDao = new TaxiDao(taxiDaoConfig, this);
        taxiPhoneDao = new TaxiPhoneDao(taxiPhoneDaoConfig, this);

        registerDao(Trayek.class, trayekDao);
        registerDao(TrayekRoute.class, trayekRouteDao);
        registerDao(TrayekWaypoint.class, trayekWaypointDao);
        registerDao(TrayekRouteDetail.class, trayekRouteDetailDao);
        registerDao(Taxi.class, taxiDao);
        registerDao(TaxiPhone.class, taxiPhoneDao);
    }
    
    public void clear() {
        trayekDaoConfig.getIdentityScope().clear();
        trayekRouteDaoConfig.getIdentityScope().clear();
        trayekWaypointDaoConfig.getIdentityScope().clear();
        trayekRouteDetailDaoConfig.getIdentityScope().clear();
        taxiDaoConfig.getIdentityScope().clear();
        taxiPhoneDaoConfig.getIdentityScope().clear();
    }

    public TrayekDao getTrayekDao() {
        return trayekDao;
    }

    public TrayekRouteDao getTrayekRouteDao() {
        return trayekRouteDao;
    }

    public TrayekWaypointDao getTrayekWaypointDao() {
        return trayekWaypointDao;
    }

    public TrayekRouteDetailDao getTrayekRouteDetailDao() {
        return trayekRouteDetailDao;
    }

    public TaxiDao getTaxiDao() {
        return taxiDao;
    }

    public TaxiPhoneDao getTaxiPhoneDao() {
        return taxiPhoneDao;
    }

}
