package com.kiri.hackjak.grdaos;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kiri.hackjak.grdaos.Trayek;
import com.kiri.hackjak.grdaos.TrayekRoute;
import com.kiri.hackjak.grdaos.TrayekWaypoint;
import com.kiri.hackjak.grdaos.TrayekRouteDetail;

import com.kiri.hackjak.grdaos.TrayekDao;
import com.kiri.hackjak.grdaos.TrayekRouteDao;
import com.kiri.hackjak.grdaos.TrayekWaypointDao;
import com.kiri.hackjak.grdaos.TrayekRouteDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trayekDaoConfig;
    private final DaoConfig trayekRouteDaoConfig;
    private final DaoConfig trayekWaypointDaoConfig;
    private final DaoConfig trayekRouteDetailDaoConfig;

    private final TrayekDao trayekDao;
    private final TrayekRouteDao trayekRouteDao;
    private final TrayekWaypointDao trayekWaypointDao;
    private final TrayekRouteDetailDao trayekRouteDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trayekDaoConfig = daoConfigMap.get(TrayekDao.class).clone();
        trayekDaoConfig.initIdentityScope(type);

        trayekRouteDaoConfig = daoConfigMap.get(TrayekRouteDao.class).clone();
        trayekRouteDaoConfig.initIdentityScope(type);

        trayekWaypointDaoConfig = daoConfigMap.get(TrayekWaypointDao.class).clone();
        trayekWaypointDaoConfig.initIdentityScope(type);

        trayekRouteDetailDaoConfig = daoConfigMap.get(TrayekRouteDetailDao.class).clone();
        trayekRouteDetailDaoConfig.initIdentityScope(type);

        trayekDao = new TrayekDao(trayekDaoConfig, this);
        trayekRouteDao = new TrayekRouteDao(trayekRouteDaoConfig, this);
        trayekWaypointDao = new TrayekWaypointDao(trayekWaypointDaoConfig, this);
        trayekRouteDetailDao = new TrayekRouteDetailDao(trayekRouteDetailDaoConfig, this);

        registerDao(Trayek.class, trayekDao);
        registerDao(TrayekRoute.class, trayekRouteDao);
        registerDao(TrayekWaypoint.class, trayekWaypointDao);
        registerDao(TrayekRouteDetail.class, trayekRouteDetailDao);
    }
    
    public void clear() {
        trayekDaoConfig.getIdentityScope().clear();
        trayekRouteDaoConfig.getIdentityScope().clear();
        trayekWaypointDaoConfig.getIdentityScope().clear();
        trayekRouteDetailDaoConfig.getIdentityScope().clear();
    }

    public TrayekDao getTrayekDao() {
        return trayekDao;
    }

    public TrayekRouteDao getTrayekRouteDao() {
        return trayekRouteDao;
    }

    public TrayekWaypointDao getTrayekWaypointDao() {
        return trayekWaypointDao;
    }

    public TrayekRouteDetailDao getTrayekRouteDetailDao() {
        return trayekRouteDetailDao;
    }

}
