package com.kiri.hackjak.sqlite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kiri.hackjak.sqlite.Trayek;
import com.kiri.hackjak.sqlite.TrayekWaypoint;

import com.kiri.hackjak.sqlite.TrayekDao;
import com.kiri.hackjak.sqlite.TrayekWaypointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trayekDaoConfig;
    private final DaoConfig trayekWaypointDaoConfig;

    private final TrayekDao trayekDao;
    private final TrayekWaypointDao trayekWaypointDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trayekDaoConfig = daoConfigMap.get(TrayekDao.class).clone();
        trayekDaoConfig.initIdentityScope(type);

        trayekWaypointDaoConfig = daoConfigMap.get(TrayekWaypointDao.class).clone();
        trayekWaypointDaoConfig.initIdentityScope(type);

        trayekDao = new TrayekDao(trayekDaoConfig, this);
        trayekWaypointDao = new TrayekWaypointDao(trayekWaypointDaoConfig, this);

        registerDao(Trayek.class, trayekDao);
        registerDao(TrayekWaypoint.class, trayekWaypointDao);
    }
    
    public void clear() {
        trayekDaoConfig.getIdentityScope().clear();
        trayekWaypointDaoConfig.getIdentityScope().clear();
    }

    public TrayekDao getTrayekDao() {
        return trayekDao;
    }

    public TrayekWaypointDao getTrayekWaypointDao() {
        return trayekWaypointDao;
    }

}
