package com.kiri.hackjak.sqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRAYEK.
 */
public class Trayek {

    private Long _id;
    private String id;
    /** Not-null value. */
    private String notrayek;
    /** Not-null value. */
    private String kategori;
    private String namasingkat;
    private String route;

    public Trayek() {
    }

    public Trayek(Long _id) {
        this._id = _id;
    }

    public Trayek(Long _id, String id, String notrayek, String kategori, String namasingkat, String route) {
        this._id = _id;
        this.id = id;
        this.notrayek = notrayek;
        this.kategori = kategori;
        this.namasingkat = namasingkat;
        this.route = route;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNotrayek() {
        return notrayek;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNotrayek(String notrayek) {
        this.notrayek = notrayek;
    }

    /** Not-null value. */
    public String getKategori() {
        return kategori;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKategori(String kategori) {
        this.kategori = kategori;
    }

    public String getNamasingkat() {
        return namasingkat;
    }

    public void setNamasingkat(String namasingkat) {
        this.namasingkat = namasingkat;
    }

    public String getRoute() {
        return route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

}
